### PR TITLE
Refactor/table configuration

### PR DESCRIPTION
**Pull request by Kaskyi**
Why
- inconsistent naming of interfaces.
- not corresponding its responsibility.

Refactor Dynamics and Table
Update interfaces name, structure, relation.
Add `XmDynamicLayout`

BREAKING CHANGES
Rename `XmPresentationLayout` to `XmDynamicPresentationLayout`
Rename `FiltersControlRequestOptions` to `XmTableFiltersControlRequestConfig`
Rename `IConfig` to `XmConfig`
Rename `table` to `table-widget`
Table change config.collection structure.

### CODE REVIEW

**Comment by sergeysenja1992** [comment]
Rename XmPresentationLayout to XmDynamicPresentationLayout
Rename XmLayout to XmDynamicLayout
Rename FiltersControlRequestOptions to XmTableFiltersControlRequestConfig
Rename IConfig to XmConfig


For what? What a goal of this breaking changes?

**Review by sergeysenja1992 — CHANGES_REQUESTED** [review]
Rename XmPresentationLayout to XmDynamicPresentationLayout
Rename XmLayout to XmDynamicLayout
Rename FiltersControlRequestOptions to XmTableFiltersControlRequestConfig
Rename IConfig to XmConfig

For what? What a goal of this breaking changes?

**Comment by sergeysenja1992** [comment]
XmLayout

**Comment by Kaskyi** [comment]
> XmLayout

done

**Review by sergeysenja1992 — APPROVED** [review]

**Review by denisogolubev — APPROVED** [review]

**Review by Olensavchenko — APPROVED** [review]

**Review by Sumragen — APPROVED** [review]

**Comment by Kaskyi** [comment]
merged iin release

**Pull request merged**
